### ISSUE TITLE
Append child and get child's Match object

### ISSUE THREAD

**Issue by bagerman** [jOOQ/jOOX#138] opened 2015-11-07 19:12 UTC
Right now to construct 

```xml
<books>
<book author="author1"/>
<book author="author2"/>
....
</books>
```

I'd do the following:

```java
Match books = $("books");
for(i=0; i < 1000; i++) {
   books.append($("book").attr("author", "author" + i));
}
```

It appears that $(String name) is quite expensive call, probably due to the builder() call. Constructing the same document  was 20 times slower than its parsing and profiling zeroed in on $("xxx") calls. 

Is there a way to append a node to the existing Match object and get corresponding to the newly created node Match object back? I am thinking about doing something like this 

```java
books.append("book");
books.children().last().attr("author", "author" + i);
```

but am not sure if it's guarantied to get the last appended child.

**Comment by lukaseder** [comment] 2015-11-10 09:03
Thanks for your suggestion. We're aware of this issue (#56). Thus far, we haven't yet fully thought through how to best resolve this. I like the API and would like to optimise only on the materialisation of the XML tree, not the API.

> but am not sure if it's guarantied to get the last appended child.

Why not? If no one concurrently modifies your document? `append()` appends at the end, and `children().last()` provides the last child...

**Comment by lukaseder** [comment] 2015-11-10 09:03
Closing this as a duplicate of #56

**Closed by lukaseder** 2015-11-10 09:03 UTC
Labels: P: Medium, T: enhancement
